# 机器学习笔记

## 加载环境，numpy pandas sklearn

In [5]:
%run venv.py

## numpy 基础方法

In [6]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
np.zeros(shape=(3,5), dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [9]:
np.ones(shape=(3,5), dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [10]:
np.full(shape=(3,5), fill_value=5.0)

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

## arange

In [11]:
[i for i in range(0, 20, 2)]

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [12]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [13]:
[i for i in range(0, 20, 0.2)]

TypeError: 'float' object cannot be interpreted as an integer

In [14]:
np.arange(0, 20, 0.2)

array([ 0. ,  0.2,  0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ,
        2.2,  2.4,  2.6,  2.8,  3. ,  3.2,  3.4,  3.6,  3.8,  4. ,  4.2,
        4.4,  4.6,  4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,  6.2,  6.4,
        6.6,  6.8,  7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,  8.4,  8.6,
        8.8,  9. ,  9.2,  9.4,  9.6,  9.8, 10. , 10.2, 10.4, 10.6, 10.8,
       11. , 11.2, 11.4, 11.6, 11.8, 12. , 12.2, 12.4, 12.6, 12.8, 13. ,
       13.2, 13.4, 13.6, 13.8, 14. , 14.2, 14.4, 14.6, 14.8, 15. , 15.2,
       15.4, 15.6, 15.8, 16. , 16.2, 16.4, 16.6, 16.8, 17. , 17.2, 17.4,
       17.6, 17.8, 18. , 18.2, 18.4, 18.6, 18.8, 19. , 19.2, 19.4, 19.6,
       19.8])

## linspace

In [15]:
np.linspace(0, 20, 5)

array([ 0.,  5., 10., 15., 20.])

In [16]:
np.linspace(0, 20, 10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [17]:
np.linspace(0,20,11)

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

## random

In [18]:
np.random.randint(4,8,size=10)

array([5, 6, 4, 7, 5, 7, 4, 7, 7, 4])

In [19]:
np.random.randint(4,8,size=(3,4))

array([[6, 4, 4, 7],
       [7, 6, 7, 4],
       [6, 5, 6, 4]])

In [20]:
np.random.seed(666)
np.random.randint(4,8,size=(3,5))

array([[4, 6, 5, 6, 6],
       [6, 5, 6, 4, 5],
       [7, 6, 7, 4, 7]])

In [21]:
np.random.seed(666)
np.random.randint(4,8,size=(3,5))

array([[4, 6, 5, 6, 6],
       [6, 5, 6, 4, 5],
       [7, 6, 7, 4, 7]])

In [22]:
np.random.random(10)

array([0.28116849, 0.46284169, 0.23340091, 0.76706421, 0.81995656,
       0.39747625, 0.31644109, 0.15551206, 0.73460987, 0.73159555])

In [23]:
np.random.random((3,5))

array([[0.8578588 , 0.76741234, 0.95323137, 0.29097383, 0.84778197],
       [0.3497619 , 0.92389692, 0.29489453, 0.52438061, 0.94253896],
       [0.07473949, 0.27646251, 0.4675855 , 0.31581532, 0.39016259]])

In [24]:
np.random.normal((1,4),1,size=(1,2))

array([[1.90472662, 3.17371673]])

In [25]:
help(np.random.normal)

Help on built-in function normal:

normal(...) method of numpy.random.mtrand.RandomState instance
    normal(loc=0.0, scale=1.0, size=None)
    
    Draw random samples from a normal (Gaussian) distribution.
    
    The probability density function of the normal distribution, first
    derived by De Moivre and 200 years later by both Gauss and Laplace
    independently [2]_, is often called the bell curve because of
    its characteristic shape (see the example below).
    
    The normal distributions occurs often in nature.  For example, it
    describes the commonly occurring distribution of samples influenced
    by a large number of tiny, random disturbances, each with its own
    unique distribution [2]_.
    
    Parameters
    ----------
    loc : float or array_like of floats
        Mean ("centre") of the distribution.
    scale : float or array_like of floats
        Standard deviation (spread or "width") of the distribution. Must be
        non-negative.
    size : int or 

## numpy array 基本操作

In [26]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
X = np.arange(15).reshape(3,5)
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

### 基本属性

In [28]:
x.ndim

1

In [29]:
X.ndim

2

In [30]:
x.shape

(10,)

In [31]:
X.shape

(3, 5)

In [32]:
x.size

10

In [33]:
X.size

15

### numpy array 数据访问

In [34]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [36]:
x[1]

1

In [37]:
X[(0,0)]

0

In [38]:
X[2,4]

14

In [39]:
x[0:5]

array([0, 1, 2, 3, 4])

In [40]:
x[:5]

array([0, 1, 2, 3, 4])

In [41]:
x[5:]

array([5, 6, 7, 8, 9])

In [42]:
x[::2]

array([0, 2, 4, 6, 8])

In [43]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [44]:
X[:2, :3]

array([[0, 1, 2],
       [5, 6, 7]])

In [45]:
X[:2][:3]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [46]:
X[:2, ::2]

array([[0, 2, 4],
       [5, 7, 9]])

In [47]:
X[:2, 2:3]

array([[2],
       [7]])

In [48]:
X[0 :]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [49]:
X[0]

array([0, 1, 2, 3, 4])

In [50]:
X[0, :]

array([0, 1, 2, 3, 4])

In [51]:
X[0, :].ndim

1

In [52]:
X[:, 0]

array([ 0,  5, 10])

In [53]:
subX = X[:2, :3]
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [54]:
subX[0, 0] = 100
subX

array([[100,   1,   2],
       [  5,   6,   7]])

In [55]:
X

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

In [56]:
subX[0, 0] = 0

In [57]:
subX = X[:2, :3].copy()
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [58]:
subX[0,0]=100
subX

array([[100,   1,   2],
       [  5,   6,   7]])

In [59]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

## reshape

In [60]:
x.shape

(10,)

In [61]:
x.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [62]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
x.reshape(1,10)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [64]:
x.reshape(1,10).shape

(1, 10)

In [65]:
x.reshape(10,-1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [66]:
x.reshape(2, -1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### 合并操作

In [68]:
x = np.array([1,2,3])
y = np.array([3,2,1])

In [69]:
x

array([1, 2, 3])

In [70]:
y

array([3, 2, 1])

In [71]:
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [72]:
z = np.array([678, 965, 323])

In [73]:
np.concatenate([x,y,z])

array([  1,   2,   3,   3,   2,   1, 678, 965, 323])

In [74]:
A = np.array([
    [1,2,3],
    [4,5,6],
])

In [75]:
np.concatenate([A, A])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [76]:
np.concatenate([A, A], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [77]:
np.concatenate([A, A], axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [78]:
np.concatenate([A, z])

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [79]:
z.reshape(1, -1)

array([[678, 965, 323]])

In [80]:
A2 = np.concatenate([A,z.reshape(1,-1)])

In [81]:
A2

array([[  1,   2,   3],
       [  4,   5,   6],
       [678, 965, 323]])

In [82]:
np.vstack([A, z])

array([[  1,   2,   3],
       [  4,   5,   6],
       [678, 965, 323]])

In [83]:
b = np.full((2,2),fill_value=100)

In [84]:
b

array([[100, 100],
       [100, 100]])

In [85]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [86]:
np.hstack([A, b])

array([[  1,   2,   3, 100, 100],
       [  4,   5,   6, 100, 100]])

### 分割操作

In [87]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [88]:
np.split(x, [3,7])

[array([0, 1, 2]), array([3, 4, 5, 6]), array([7, 8, 9])]

In [89]:
np.split(x, [3,])

[array([0, 1, 2]), array([3, 4, 5, 6, 7, 8, 9])]

In [90]:
A = np.arange(16).reshape(4,4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [91]:
np.split(A, [2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [92]:
np.split(A, [1,3])


[array([[0, 1, 2, 3]]), array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]), array([[12, 13, 14, 15]])]

In [93]:
A1, A2 = np.split(A, [2], axis=1)

In [94]:
A1

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [95]:
A2

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [96]:
uper, lower = np.vsplit(A, [2])

In [97]:
uper

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [98]:
lower

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [99]:
left, right = np.hsplit(A, [2])

In [100]:
left

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [101]:
right

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [102]:
x, y = np.hsplit(A, [-1])

In [103]:
x

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])

In [104]:
y

array([[ 3],
       [ 7],
       [11],
       [15]])

In [105]:
y[:,0]

array([ 3,  7, 11, 15])

## numpy array 矩阵运算

给定一个向量，让向量每一个数*2

a = (0, 1, 2)

a*2 = (0, 2, 4)



In [106]:
n = 10
L = [_ for _ in range(n)]

In [107]:
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [108]:
L*2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [109]:
%%time
[i*2 for i in L]

CPU times: user 7 µs, sys: 1e+03 ns, total: 8 µs
Wall time: 11 µs


[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [110]:
%%time
a = []
for i in L:
    a.append(i*2)

CPU times: user 5 µs, sys: 0 ns, total: 5 µs
Wall time: 7.87 µs


In [111]:
L = np.arange(n)

In [112]:
%%time
[i*2 for i in L]

CPU times: user 20 µs, sys: 1 µs, total: 21 µs
Wall time: 24.1 µs


[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [113]:
L

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [114]:
L * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

## Universal functions

In [115]:
X = np.arange(16).reshape(4,4)

In [116]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [117]:
X + 1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [118]:
X - 1

array([[-1,  0,  1,  2],
       [ 3,  4,  5,  6],
       [ 7,  8,  9, 10],
       [11, 12, 13, 14]])

In [119]:
X * 2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22],
       [24, 26, 28, 30]])

In [120]:
X / 2

array([[0. , 0.5, 1. , 1.5],
       [2. , 2.5, 3. , 3.5],
       [4. , 4.5, 5. , 5.5],
       [6. , 6.5, 7. , 7.5]])

In [121]:
X // 2

array([[0, 0, 1, 1],
       [2, 2, 3, 3],
       [4, 4, 5, 5],
       [6, 6, 7, 7]])

In [122]:
X ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121],
       [144, 169, 196, 225]])

In [123]:
X % 2

array([[0, 1, 0, 1],
       [0, 1, 0, 1],
       [0, 1, 0, 1],
       [0, 1, 0, 1]])

In [124]:
1 / X

/Users/johnnyleaf/Documents/Preject/MachineLearning/mclearn-venv/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[       inf, 1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667, 0.14285714],
       [0.125     , 0.11111111, 0.1       , 0.09090909],
       [0.08333333, 0.07692308, 0.07142857, 0.06666667]])

In [125]:
np.abs(X)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [126]:
np.cos(X)

array([[ 1.        ,  0.54030231, -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029,  0.75390225],
       [-0.14550003, -0.91113026, -0.83907153,  0.0044257 ],
       [ 0.84385396,  0.90744678,  0.13673722, -0.75968791]])

In [127]:
np.sin(X)

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849, -0.54402111, -0.99999021],
       [-0.53657292,  0.42016704,  0.99060736,  0.65028784]])

In [129]:
np.tan(X)

array([[ 0.00000000e+00,  1.55740772e+00, -2.18503986e+00,
        -1.42546543e-01],
       [ 1.15782128e+00, -3.38051501e+00, -2.91006191e-01,
         8.71447983e-01],
       [-6.79971146e+00, -4.52315659e-01,  6.48360827e-01,
        -2.25950846e+02],
       [-6.35859929e-01,  4.63021133e-01,  7.24460662e+00,
        -8.55993401e-01]])

In [130]:
np.exp(X)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04],
       [1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06]])

In [132]:
np.power(3, X)

array([[       1,        3,        9,       27],
       [      81,      243,      729,     2187],
       [    6561,    19683,    59049,   177147],
       [  531441,  1594323,  4782969, 14348907]])

In [133]:
np.log2(X)

/Users/johnnyleaf/Documents/Preject/MachineLearning/mclearn-venv/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log2
  """Entry point for launching an IPython kernel.


array([[      -inf, 0.        , 1.        , 1.5849625 ],
       [2.        , 2.32192809, 2.5849625 , 2.80735492],
       [3.        , 3.169925  , 3.32192809, 3.45943162],
       [3.5849625 , 3.70043972, 3.80735492, 3.9068906 ]])

### 矩阵运算

In [136]:
A = np.arange(4).reshape(2,2)
A

array([[0, 1],
       [2, 3]])

In [138]:
B = np.full((2,2), 10)
B

array([[10, 10],
       [10, 10]])

In [139]:
A + B

array([[10, 11],
       [12, 13]])

In [140]:
A - B

array([[-10,  -9],
       [ -8,  -7]])

In [141]:
A * B

array([[ 0, 10],
       [20, 30]])

In [142]:
A / B

array([[0. , 0.1],
       [0.2, 0.3]])

In [143]:
A.dot(B)

array([[10, 10],
       [50, 50]])

In [144]:
A

array([[0, 1],
       [2, 3]])

In [145]:
A.T

array([[0, 2],
       [1, 3]])

In [147]:
c = np.full((3,3), 666)
c

array([[666, 666, 666],
       [666, 666, 666],
       [666, 666, 666]])

In [148]:
A * c

ValueError: operands could not be broadcast together with shapes (2,2) (3,3) 

## 向量与矩阵运算

In [149]:
v = np.array([1,2])

In [150]:
A

array([[0, 1],
       [2, 3]])

In [151]:
v + A

array([[1, 3],
       [3, 5]])

In [152]:
np.vstack([v] * A.shape[0])

array([[1, 2],
       [1, 2]])

In [155]:
np.tile(v, (2,1))

array([[1, 2],
       [1, 2]])

In [156]:
v * A

array([[0, 2],
       [2, 6]])

In [157]:
v.dot(A)

array([4, 7])

In [158]:
A.dot(v)

array([2, 8])

## 矩阵的逆

In [159]:
A

array([[0, 1],
       [2, 3]])

In [160]:
np.linalg.inv(A)

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [161]:
X = np.arange(16).reshape((2,8))

In [162]:
X

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [163]:
np.linalg.inv(X)

LinAlgError: Last 2 dimensions of the array must be square

In [164]:
np.linalg.pinv(X)

array([[-1.35416667e-01,  5.20833333e-02],
       [-1.01190476e-01,  4.16666667e-02],
       [-6.69642857e-02,  3.12500000e-02],
       [-3.27380952e-02,  2.08333333e-02],
       [ 1.48809524e-03,  1.04166667e-02],
       [ 3.57142857e-02, -7.30583920e-18],
       [ 6.99404762e-02, -1.04166667e-02],
       [ 1.04166667e-01, -2.08333333e-02]])